# Generated by Django 3.2.19 on 2023-06-27 09:23

import django.core.validators
from django.db import migrations, models
import musicapp.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), musicapp.web.validators.contains_only_letters_numbers_and_underscore]),
        ),
    ]
